; ============================================================
;  Meshtastic Tracker Display — T-Deck build
;  platformio.ini
; ============================================================

[platformio]
default_envs = t-deck-tracker-display

[env:t-deck-tracker-display]
extends     = env:t-deck
build_type  = release

build_src_filter =
    +<*>
    +<../tdeck-display/src/**>

build_flags =
    ${env:t-deck.build_flags}
    -DUSE_TRACKER_DISPLAY_MODULE=1
